server:
  port: 8000

spring:
  cloud:
    gateway:
      routes:
        - id: first-service
          uri: http://localhost:8081/
          predicates:
            - Path=/first-service/**
        - id: first-service
          uri: http://localhost:8081/
          predicates:
            - Path=/second-service/**


