server:
  port: 8081

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/YoonSeungKwon/ConfigTest1.git
          default-label: main
          search-paths: config
