server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    username: root
    password: 1149
    url: jdbc:mariadb://localhost:3306/cloud
    driver-class-name: org.mariadb.jdbc.Driver

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka





